org: jaysonani
app: plasmatic-project
service: plasmatic-project
frameworkVersion: "3"

# AWS Cloud Provider
provider:
  name: aws
  runtime: nodejs16.x

  # Setting environment variables
  environment:
    DYNAMODB_TABLE_PETS: ${self:service}-petsTable-${sls:stage}

  # Granting permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Sid: AccessTableAllIndexesOnBooks
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:ConditionCheckIte
          Resource:
            - arn:aws:dynamodb:us-east-1:359996502019:table/plasmatic-project-petsTable-dev
            - arn:aws:dynamodb:us-east-1:359996502019:table/plasmatic-project-petsTable-dev/index/*
            # arn:aws:dynamodb:${aws.region}:${aws:accountId}:table/${self:service}-petsTable-${sls:stage}

# API Endpoints
functions:
  plasmatic:
    handler: handler.plasmatic
    events:
      - httpApi:
          path: /
          method: get

  addPet:
    handler: lambdas/pet/addPet.handler
    events:
      - httpApi:
          path: /pet
          method: post

  updatePet:
    handler: lambdas/pet/updatePet.handler
    events:
      - httpApi:
          path: /pet
          method: put

  findByStatus:
    handler: lambdas/pet/findByStatus.handler
    events:
      - httpApi:
          path: /pet/findByStatus
          method: get

  findById:
    handler: lambdas/pet/findById.handler
    events:
      - httpApi:
          path: /pet/{petId}
          method: get

  updatePetById:
    handler: lambdas/pet/updatePetById.handler
    events:
      - httpApi:
          path: /pet/{petId}
          method: post

  deletePet:
    handler: lambdas/pet/deletePet.handler
    events:
      - httpApi:
          path: /pet/{petId}
          method: delete

  placeOrder:
    handler: lambdas/store/placeOrder.handler
    events:
      - httpApi:
          path: /store/order
          method: post

# Resource creation
resources:
  Resources:
    PetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-petsTable-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: status
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: status-index
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: id-index
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-ordersTable-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          # - AttributeName: status
          #   AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # GlobalSecondaryIndexes:
        #   - IndexName: status-index
        #     KeySchema:
        #       - AttributeName: status
        #         KeyType: HASH
        #     Projection:
        #       ProjectionType: ALL
        #   - IndexName: id-index
        #     KeySchema:
        #       - AttributeName: id
        #         KeyType: HASH
        #     Projection:
        #       ProjectionType: ALL
